---
- name: Update and upgrade
  become: yes
  packages:
    upgrade: yes
    update_cache: yes

- name: Run installation
  become: yes
  with_items: "{{ installation_pkg }}"
  packages:
    pkg: "{{ item.name }}"
    state: latest

- name: Create custom index.html
  become: yes
  template:
    src:"index.html.j2"
    dest:"/var/www/html/index.html"

- name: Set file stats on index.html
  file:
    path:"/var/www/html/index.html"
    owner: root
    group: root
    mode: 0644

- name: Deploy modified apache conf
  copy:
    src: "apache2.conf"
    dest: "/etc/apache2/apache2.conf"
    owner: root
    group: root
    mode: 0644

- name: Enable mod_headers
  file:
    path: "/etc/apache2/mods-enabled/headers.load"
    src: "/etc/apache2/mods-available/headers.load"
    state: link

- name: Re-start apache
  service:
    name: apache2
    state: restarted
